filter:
    excluded_paths: [vendor/*, tests/*]

tools:
    php_mess_detector: true
    php_cpd: true
    php_pdepend:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
    php_code_coverage: true
    php_loc: true
    sensiolabs_security_checker: true

before_commands:
    - "composer install --prefer-source"
